import Link from "next/link";
import { ArrowRight, Building2, CalendarClock, CircleDollarSign, Target, TrendingUp, Users } from "lucide-react";
import { Badge, PageHeader } from "@/components/ui";
import { bids, companies, contacts, followUps } from "@/lib/demo-data";

export default function Dashboard() {
  const averageScore = Math.round(companies.reduce((sum, company) => sum + company.lead_score, 0) / companies.length);
  const registrationReady = companies.filter((company) => company.invite_list_status?.toLowerCase().includes("registration") || company.invite_list_status?.toLowerCase().includes("portal") || company.invite_list_status?.toLowerCase().includes("prequalification") || company.invite_list_status?.toLowerCase().includes("trade partner")).length;
  const metrics = [
    ["Verified buyers", String(companies.length), "KC launch dataset", Building2], ["Public contacts", String(contacts.length), "Organization-level", Users],
    ["Ready to register", String(registrationReady), "Bid-list pathways", Target], ["Live bid value", "$0", "Feed connection next", CircleDollarSign],
    ["Due follow-ups", String(followUps.length), "Needs attention", CalendarClock], ["Average fit score", String(averageScore), "KC metalwork fit", TrendingUp],
  ] as const;
  return <><PageHeader eyebrow="Kansas City launch market" title="Your route onto more bid lists." description="Verified buyers, public registration paths, and the next actions that can create fabrication opportunities." action={<Link href="/companies" className="rounded-lg bg-ink px-4 py-2.5 text-sm font-semibold text-white">Browse buyers</Link>}/>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{metrics.map(([label, value, sub, Icon]) => <div className="card p-4" key={label}><div className="mb-4 flex items-center justify-between"><Icon size={17} className="text-moss"/><span className="size-1.5 rounded-full bg-emerald-400"/></div><p className="text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs font-semibold text-slate-700">{label}</p><p className={`mt-2 text-[11px] ${label === "Due follow-ups" ? "text-red-600" : "text-slate-400"}`}>{sub}</p></div>)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-serif text-lg font-semibold">Highest-scoring leads</h2><p className="text-xs text-slate-400">Best opportunities based on your scoring rules</p></div><Link href="/companies" className="text-xs font-bold text-brand">View all →</Link></div><div className="divide-y divide-slate-100">{companies.slice(0,5).map((c, i) => <Link href={`/companies/${c.company_id}`} key={c.company_id} className="flex items-center gap-4 px-5 py-3.5 hover:bg-slate-50"><span className="w-4 text-xs text-slate-300">{i+1}</span><div className="grid size-9 place-items-center rounded-lg bg-moss/10 text-xs font-bold text-moss">{c.company_name.split(" ").slice(0,2).map(x=>x[0]).join("")}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-ink">{c.company_name}</p><p className="truncate text-xs text-slate-400">{c.specialization} · {c.city}, {c.state}</p></div><Badge tone={c.lead_status === "Qualified" ? "green" : "blue"}>{c.lead_status}</Badge><div className="w-9 text-right text-lg font-bold text-ink">{c.lead_score}</div></Link>)}</div></div>
      <div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-serif text-lg font-semibold">Upcoming follow-ups</h2><p className="text-xs text-slate-400">Your next actions</p></div><Link href="/follow-ups" className="text-xs font-bold text-brand">View all →</Link></div><div className="divide-y divide-slate-100">{followUps.map(f => <div key={f.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{f.task}</p><p className="mt-1 text-xs text-slate-400">{f.company} · {f.contact}</p></div><Badge tone={f.due === "Today" ? "red" : "orange"}>{f.due}</Badge></div></div>)}</div></div></section>
    <section className="card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-serif text-lg font-semibold">Live bid opportunities</h2><p className="text-xs text-slate-400">Only source-verified opportunities will appear here</p></div><Link href="/bids" className="flex items-center gap-1 text-xs font-bold text-brand">Bid board <ArrowRight size={13}/></Link></div>{bids.length?<div className="overflow-x-auto"><table><thead><tr><th>Project</th><th>Company</th><th>Due</th><th>Value</th><th>Probability</th><th>Status</th></tr></thead><tbody>{bids.map(b => <tr key={b.id}><td className="font-semibold text-ink">{b.project}</td><td>{b.company}</td><td>{b.due}</td><td>${b.value.toLocaleString()}</td><td>{b.probability}%</td><td><Badge tone="green">{b.status}</Badge></td></tr>)}</tbody></table></div>:<div className="p-8 text-center"><p className="font-semibold">No invented opportunities</p><p className="mt-1 text-sm text-slate-500">Connect KCMO, MissouriBUYS, SAM.gov and partner feeds to populate current projects.</p></div>}</section>
  </>;
}
