import { Bid, Company, Contact, FollowUp } from "./types";

export const companies: Company[] = [
  { company_id: "1", company_name: "McCownGordon Construction", company_type: "General Contractor / CM", city: "Kansas City", state: "MO", specialization: "Commercial, civic, education, healthcare and industrial construction", lead_status: "Qualified", lead_score: 96, distance_from_base_miles: 1, public_phone: "888-304-4929", website: "https://www.mccowngordon.com", prequalification_url: "https://www.mccowngordon.com/contact-us/trade-partner-prequalification/", bid_portal_url: "https://www.mccowngordon.com/contact-us/trade-partner-prequalification/", source_url: "https://www.mccowngordon.com/", invite_list_status: "Trade partner prequalification", typical_scopes: "Structural steel, miscellaneous metals, stairs, rails, embeds, canopies and architectural metals", data_verified_at: "2026-07-08", notes: "Official site lists Kansas City office and trade partner prequalification. Strong first outreach target for fabrication bid invites." },
  { company_id: "2", company_name: "JE Dunn Construction", company_type: "National General Contractor / CM", city: "Kansas City", state: "MO", specialization: "Healthcare, education, civic, commercial and industrial construction", lead_status: "Qualified", lead_score: 95, distance_from_base_miles: 1, public_phone: "(816) 474-8600", website: "https://www.jedunn.com", prequalification_url: "https://www.jedunn.com/trade-partners", bid_portal_url: "https://www.jedunn.com/trade-partners", source_url: "https://www.jedunn.com/", invite_list_status: "Trade partner page available", typical_scopes: "Steel packages, stairs, rails, metals, supports, ladders, embeds and specialty fabrication", data_verified_at: "2026-07-08", notes: "Official site includes Trade Partners navigation. Request estimating/vendor onboarding for KC-region projects." },
  { company_id: "3", company_name: "Turner Construction Company", company_type: "National General Contractor / CM", city: "Kansas City", state: "MO", specialization: "Commercial, healthcare, education, sports, civic and advanced technology", lead_status: "New", lead_score: 92, distance_from_base_miles: 4, website: "https://www.turnerconstruction.com", prequalification_url: "https://www.turnerconstruction.com/sub-contractors", bid_portal_url: "https://www.turnerconstruction.com/sub-contractors", source_url: "https://www.turnerconstruction.com/", invite_list_status: "Subcontractor information available", typical_scopes: "Structural and miscellaneous metals, stairs, rails, ladders, platforms and embeds", data_verified_at: "2026-07-08", notes: "National builder with subcontractor information. Contact regional office and complete vendor onboarding before requesting invitations." },
  { company_id: "4", company_name: "Burns & McDonnell", company_type: "Engineering / EPC / Construction", city: "Kansas City", state: "MO", specialization: "Industrial, power, aviation, manufacturing, infrastructure and facilities", lead_status: "Qualified", lead_score: 91, distance_from_base_miles: 8, public_phone: "(816) 333-9400", website: "https://www.burnsmcd.com", source_url: "https://www.burnsmcd.com/", invite_list_status: "Supplier outreach needed", typical_scopes: "Industrial steel, platforms, pipe supports, equipment supports, stairs, rails and plant fabrication", data_verified_at: "2026-07-08", notes: "Kansas City-headquartered EPC firm. Best fit for industrial fabrication shops with safety documentation and project references." },
  { company_id: "5", company_name: "Black & Veatch", company_type: "Engineering / EPC / Infrastructure", city: "Overland Park", state: "KS", specialization: "Power, water, industrial, telecom and critical infrastructure", lead_status: "New", lead_score: 90, distance_from_base_miles: 13, public_phone: "(913) 458-2000", website: "https://www.bv.com", source_url: "https://www.bv.com/", invite_list_status: "Supplier registration research", typical_scopes: "Industrial metals, platforms, access steel, supports, skids and utility infrastructure fabrication", data_verified_at: "2026-07-08", notes: "Large EPC/infrastructure buyer. Good target for fabrication shops that can support engineered industrial packages." },
  { company_id: "6", company_name: "HNTB Corporation", company_type: "Infrastructure Design / CM", city: "Kansas City", state: "MO", specialization: "Transportation, bridges, aviation, transit and public infrastructure", lead_status: "New", lead_score: 86, distance_from_base_miles: 2, website: "https://www.hntb.com", source_url: "https://www.hntb.com/", invite_list_status: "Partner outreach needed", typical_scopes: "Bridge-related metals, railings, platforms, transit structures and infrastructure fabrication", data_verified_at: "2026-07-08", notes: "Infrastructure firm; fabrication shops should pursue teaming/subconsultant and contractor partner introductions." },
  { company_id: "7", company_name: "Kiewit", company_type: "Heavy Civil / Industrial Contractor", city: "Lenexa", state: "KS", specialization: "Transportation, power, water, industrial and infrastructure construction", lead_status: "Qualified", lead_score: 89, distance_from_base_miles: 16, website: "https://www.kiewit.com", source_url: "https://www.kiewit.com/", invite_list_status: "Supplier/subcontractor outreach needed", typical_scopes: "Heavy civil steel, bridge metals, platforms, handrail, ladders and industrial supports", data_verified_at: "2026-07-08", notes: "Major heavy civil and industrial contractor with strong fit for certified fabrication suppliers." },
  { company_id: "8", company_name: "Clarkson Construction Company", company_type: "Heavy Civil Contractor", city: "Kansas City", state: "MO", specialization: "Transportation, bridges, sitework, concrete and infrastructure", lead_status: "New", lead_score: 85, distance_from_base_miles: 6, website: "https://www.clarksonconstruction.com", source_url: "https://www.clarksonconstruction.com/", invite_list_status: "Estimating outreach needed", typical_scopes: "Bridge rail, guardrail supports, miscellaneous metals, embeds, platforms and repair fabrication", data_verified_at: "2026-07-08", notes: "Kansas City heavy civil contractor. Good fit for shops comfortable with infrastructure schedules and DOT requirements." },
  { company_id: "9", company_name: "Kissick Construction Company", company_type: "Heavy Civil / Utility Contractor", city: "Kansas City", state: "MO", specialization: "Water, wastewater, transportation, energy and industrial construction", lead_status: "New", lead_score: 84, distance_from_base_miles: 6, website: "https://www.kissickco.com", source_url: "https://www.kissickco.com/", invite_list_status: "Estimating outreach needed", typical_scopes: "Access platforms, railings, hatches, supports, plant metals, pipe supports and utility fabrication", data_verified_at: "2026-07-08", notes: "Strong fit for water/wastewater and infrastructure metal packages." },
  { company_id: "10", company_name: "MegaKC", company_type: "General / Civil Contractor", city: "Kansas City", state: "MO", specialization: "Industrial, commercial, civil, concrete and public works", lead_status: "Qualified", lead_score: 86, distance_from_base_miles: 8, public_phone: "(816) 444-7000", website: "https://megakc.com", source_url: "https://megakc.com/", invite_list_status: "Estimating outreach needed", typical_scopes: "Industrial platforms, stairs, railings, embeds, steel supports and specialty fabricated items", data_verified_at: "2026-07-08", notes: "Kansas City contractor with industrial/civil fit. Ask estimating how to be added to bid lists." },
  { company_id: "11", company_name: "A.L. Huber General Contractor", company_type: "General Contractor", city: "Overland Park", state: "KS", specialization: "Commercial, civic, education, healthcare and interiors", lead_status: "New", lead_score: 83, distance_from_base_miles: 14, public_phone: "(913) 341-4880", website: "https://www.alhuber.com", source_url: "https://www.alhuber.com/", invite_list_status: "Trade partner outreach needed", typical_scopes: "Stairs, handrails, guardrails, lintels, canopies, bollards and miscellaneous metals", data_verified_at: "2026-07-08", notes: "Regional GC. Good bid-list target for small-to-mid fabrication shops with commercial references." },
  { company_id: "12", company_name: "MW Builders", company_type: "General Contractor", city: "Lenexa", state: "KS", specialization: "Commercial, multifamily, senior living, hospitality and industrial", lead_status: "New", lead_score: 84, distance_from_base_miles: 16, website: "https://www.mwbuilders.com", source_url: "https://www.mwbuilders.com/", invite_list_status: "Trade partner outreach needed", typical_scopes: "Stairs, rails, balconies, embeds, bollards, ladders and miscellaneous metals", data_verified_at: "2026-07-08", notes: "Regional/national builder with Kansas presence. Request subcontractor prequalification path." },
  { company_id: "13", company_name: "Crossland Construction", company_type: "General Contractor / Self-Perform Builder", city: "Kansas City", state: "MO", specialization: "Commercial, education, industrial, healthcare and public projects", lead_status: "New", lead_score: 85, distance_from_base_miles: 8, website: "https://www.crossland.com", source_url: "https://www.crossland.com/", invite_list_status: "Subcontractor outreach needed", typical_scopes: "Commercial metals, stairs, rails, supports, structural steel coordination and embeds", data_verified_at: "2026-07-08", notes: "Large regional builder. Good target for shops that can support repeat commercial packages." },
  { company_id: "14", company_name: "The Weitz Company", company_type: "General Contractor / CM", city: "Lenexa", state: "KS", specialization: "Commercial, industrial, aviation, senior living and mission critical", lead_status: "New", lead_score: 82, distance_from_base_miles: 16, website: "https://www.weitz.com", source_url: "https://www.weitz.com/", invite_list_status: "Trade partner outreach needed", typical_scopes: "Structural steel coordination, stairs, rails, supports, platforms and specialty fabrication", data_verified_at: "2026-07-08", notes: "National GC with regional presence. Ask for preconstruction/estimating contact for KC-area opportunities." },
  { company_id: "15", company_name: "Hensel Phelps", company_type: "National General Contractor", city: "Kansas City", state: "MO", specialization: "Aviation, federal, healthcare, education, commercial and infrastructure", lead_status: "New", lead_score: 84, distance_from_base_miles: 8, website: "https://www.henselphelps.com", source_url: "https://www.henselphelps.com/", invite_list_status: "Subcontractor registration research", typical_scopes: "Public/federal project metals, stairs, rails, ladders, platforms and specialty supports", data_verified_at: "2026-07-08", notes: "Strong fit for shops with safety program, bonding/insurance, and public-sector experience." },
  { company_id: "16", company_name: "Nabholz Construction", company_type: "General Contractor / CM", city: "Olathe", state: "KS", specialization: "Commercial, healthcare, education, industrial and service work", lead_status: "New", lead_score: 81, distance_from_base_miles: 24, website: "https://nabholz.com", source_url: "https://nabholz.com/", invite_list_status: "Trade partner outreach needed", typical_scopes: "Commercial metals, stairs, handrails, repairs, equipment supports and facility-service fabrication", data_verified_at: "2026-07-08", notes: "Regional GC/service contractor. Good fit for both bid work and recurring facilities fabrication." },
  { company_id: "17", company_name: "Straub Construction", company_type: "General Contractor", city: "Shawnee", state: "KS", specialization: "Commercial, education, municipal, religious and community projects", lead_status: "New", lead_score: 80, distance_from_base_miles: 12, website: "https://www.straubconstruction.com", source_url: "https://www.straubconstruction.com/", invite_list_status: "Estimating outreach needed", typical_scopes: "Stairs, railings, bollards, lintels, small structural packages and miscellaneous metals", data_verified_at: "2026-07-08", notes: "Good target for local fabrication shops that want GC relationships without only chasing mega-projects." },
  { company_id: "18", company_name: "Fogel-Anderson Construction", company_type: "General Contractor", city: "Kansas City", state: "MO", specialization: "Commercial, healthcare, education, civic and renovation projects", lead_status: "New", lead_score: 79, distance_from_base_miles: 4, website: "https://www.fogel-anderson.com", source_url: "https://www.fogel-anderson.com/", invite_list_status: "Estimating outreach needed", typical_scopes: "Renovation metals, stairs, guardrails, canopies, bollards and custom fabrication", data_verified_at: "2026-07-08", notes: "Local GC with practical fit for smaller fabrication packages and renovation scopes." },
  { company_id: "19", company_name: "Superior Bowen", company_type: "Infrastructure / Civil Contractor", city: "Kansas City", state: "MO", specialization: "Roadwork, asphalt, concrete, paving and infrastructure", lead_status: "New", lead_score: 76, distance_from_base_miles: 7, website: "https://superiorbowen.com", source_url: "https://superiorbowen.com/", invite_list_status: "Procurement outreach needed", typical_scopes: "Roadway metal items, supports, safety rails, miscellaneous site fabrication and repair work", data_verified_at: "2026-07-08", notes: "Best fit for shops supporting civil contractors, repair fabrication and DOT-adjacent work." },
  { company_id: "20", company_name: "Emery Sapp & Sons", company_type: "Heavy Civil Contractor", city: "Kansas City", state: "MO", specialization: "Heavy civil, utilities, grading, concrete, asphalt and infrastructure", lead_status: "New", lead_score: 78, distance_from_base_miles: 10, website: "https://emerysapp.com", source_url: "https://emerysapp.com/", invite_list_status: "Procurement outreach needed", typical_scopes: "Civil project metals, temporary works, platforms, supports, embeds and repair fabrication", data_verified_at: "2026-07-08", notes: "Regional heavy civil contractor. Good fit for shops that can respond quickly to field fabrication needs." },
  { company_id: "21", company_name: "City of Kansas City, Missouri Procurement", company_type: "Public Agency", city: "Kansas City", state: "MO", specialization: "Municipal construction, facilities, maintenance and public works", lead_status: "Qualified", lead_score: 90, distance_from_base_miles: 1, public_phone: "(816) 513-0851", website: "https://www.kcmo.gov/city-hall/departments/general-services/bids", prequalification_url: "https://www.kcmo.gov/city-hall/departments/general-services/bids", bid_portal_url: "https://www.kcmo.gov/city-hall/departments/general-services/bids", source_url: "https://www.kcmo.gov/city-hall/departments/general-services/bids", invite_list_status: "Public bid portal", typical_scopes: "Public works metals, railings, repairs, facilities, infrastructure and maintenance fabrication", data_verified_at: "2026-07-08", notes: "Official city bid page. Register/watch plan room and procurement notices for public metal packages." },
  { company_id: "22", company_name: "MissouriBUYS", company_type: "State Procurement Portal", city: "Jefferson City", state: "MO", specialization: "Statewide public procurement and facility opportunities", lead_status: "Qualified", lead_score: 82, distance_from_base_miles: 148, website: "https://missouribuys.mo.gov/", prequalification_url: "https://missouribuys.mo.gov/", bid_portal_url: "https://missouribuys.mo.gov/", source_url: "https://missouribuys.mo.gov/", invite_list_status: "Vendor registration open", typical_scopes: "State facilities, maintenance, infrastructure, materials and public construction opportunities", data_verified_at: "2026-07-08", notes: "Statewide portal for Missouri opportunities. Register for notifications by commodity/service category." },
  { company_id: "23", company_name: "Kansas City Public Schools Purchasing", company_type: "School District", city: "Kansas City", state: "MO", specialization: "K-12 facilities, capital projects and maintenance", lead_status: "Qualified", lead_score: 87, distance_from_base_miles: 4, public_phone: "(816) 418-7300", website: "https://www.kcpublicschools.org/o/kcps/page/purchasing", prequalification_url: "https://www.kcpublicschools.org/o/kcps/page/purchasing", bid_portal_url: "https://www.kcpublicschools.org/o/kcps/page/purchasing", source_url: "https://www.kcpublicschools.org/o/kcps/page/purchasing", invite_list_status: "Vendor registration / bid notices", typical_scopes: "School additions, stairs, railings, canopies, equipment supports and repair fabrication", data_verified_at: "2026-07-08", notes: "Official purchasing page. Register for bid notifications and watch facilities/capital improvement opportunities." },
  { company_id: "24", company_name: "Johnson County, Kansas Purchasing", company_type: "County Procurement", city: "Olathe", state: "KS", specialization: "County facilities, public works and infrastructure procurement", lead_status: "New", lead_score: 78, distance_from_base_miles: 23, website: "https://www.jocogov.org/department/financial-management-administration/purchasing", bid_portal_url: "https://www.jocogov.org/department/financial-management-administration/purchasing", source_url: "https://www.jocogov.org/department/financial-management-administration/purchasing", invite_list_status: "Public purchasing page", typical_scopes: "Facilities metals, public works repairs, railings, site fabrication and maintenance support", data_verified_at: "2026-07-08", notes: "Good public-sector target for Kansas-side fabrication shops." },
  { company_id: "25", company_name: "Kansas City Area Transportation Authority", company_type: "Transit Agency", city: "Kansas City", state: "MO", specialization: "Transit facilities, stops, maintenance and infrastructure", lead_status: "New", lead_score: 77, distance_from_base_miles: 2, website: "https://www.kcata.org", bid_portal_url: "https://www.kcata.org/about_kcata/entries/procurement", source_url: "https://www.kcata.org/about_kcata/entries/procurement", invite_list_status: "Procurement page", typical_scopes: "Transit-stop metals, railings, shelters, platforms, maintenance fabrication and facility repairs", data_verified_at: "2026-07-08", notes: "Public transit procurement can be a practical source of small-to-mid metal packages and maintenance work." },
];

export const contacts: Contact[] = [
  { contact_id: "c1", company_id: "21", first_name: "Procurement", last_name: "Services", title: "Public procurement office", email: "", phone: "(816) 513-0851", decision_maker: false, next_follow_up_at: "2026-07-10" },
  { contact_id: "c2", company_id: "23", first_name: "Purchasing", last_name: "Office", title: "Vendor registration and bids", email: "", phone: "(816) 418-7300", decision_maker: false, next_follow_up_at: "2026-07-10" },
  { contact_id: "c3", company_id: "1", first_name: "Trade Partner", last_name: "Prequalification", title: "Vendor onboarding path", email: "", phone: "888-304-4929", decision_maker: false, next_follow_up_at: "2026-07-11" },
  { contact_id: "c4", company_id: "2", first_name: "Trade", last_name: "Partners", title: "Subcontractor onboarding path", email: "", phone: "(816) 474-8600", decision_maker: false, next_follow_up_at: "2026-07-11" },
  { contact_id: "c5", company_id: "10", first_name: "Estimating", last_name: "Department", title: "Bid-list outreach", email: "", phone: "(816) 444-7000", decision_maker: false, next_follow_up_at: "2026-07-13" },
];

export const bids: Bid[] = [];

export const followUps: FollowUp[] = [
  { id: "f1", company: "McCownGordon Construction", contact: "Trade partner team", task: "Complete trade partner prequalification", due: "Today", priority: "High", status: "Open" },
  { id: "f2", company: "JE Dunn Construction", contact: "Trade Partners", task: "Request KC bid-list onboarding steps", due: "Tomorrow", priority: "High", status: "Open" },
  { id: "f3", company: "City of Kansas City, Missouri Procurement", contact: "Procurement Services", task: "Register and monitor public bid notices", due: "Jul 12", priority: "High", status: "Open" },
  { id: "f4", company: "Burns & McDonnell", contact: "Supplier/procurement path", task: "Ask how fabrication suppliers are qualified for industrial/EPC work", due: "Jul 15", priority: "Medium", status: "Open" },
  { id: "f5", company: "MegaKC", contact: "Estimating", task: "Send capability statement and request bid invites", due: "Jul 16", priority: "Medium", status: "Open" },
];
